# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
            ],
        ),
    ]
